# Generated by Django 2.0.7 on 2018-09-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Scheduled price of product')),
                ('date_start', models.DateField(help_text='Date this pricing schedule begins')),
                ('date_end', models.DateField(blank=True, help_text='Date this pricing schedule ends', null=True)),
                ('product', models.ForeignKey(help_text='Product to apply a scheduled price to', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
